 FROM ubuntu
RUN apt update && \
    apt-get install -y gcc make cmake wget clang pkg-config git curl zip unzip tar mosquitto libmosquitto-dev \
                   libssl-dev libboost-all-dev libssl-dev libcurl4-openssl-dev

RUN git clone https://github.com/Microsoft/vcpkg.git && \
    ./vcpkg/bootstrap-vcpkg.sh && \
    cd /vcpkg/ && \
    ./vcpkg install mosquitto tgbot-cpp boost

RUN git clone https://github.com/opencv/opencv.git && \
    mkdir -p build && cd build && \
    cmake ../opencv && \
    make -j4 && \
    make install

COPY DeliveryBot /


RUN mkdir /app

#RUN apt-get -y install libsdl-image1.2-dev

#RUN cd /vcpkg/ && ./vcpkg upgrade

COPY DeliveryBot/ /app

RUN apt-get install -y build-essential manpages-dev
RUN cd /app/ && mkdir build && cd /app/build && \
    cmake .. -DCMAKE_BUILD_TYPE=Debug && \
    cmake --build .

#RUN
RUN cd /app/build/ && ./DeliveryBotBinary
